### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by loljeffer** [Ethorbit/Anti-AFK#6]
The "README" file doesn't tell how to configure a key bind or change any of the settings. I do not code so I dont really understand the c++ code or how it works. not trying to sound like a karen, saying this cause i read through it and sounded like one but my point still stands. 

thank you for understanding 
Kind regards

**Comment by Ethorbit** [comment]
> The "README" file doesn't tell how to configure a key bind or change any of the settings. I do not code so I dont really understand the c++ code or how it works. not trying to sound like a karen, saying this cause i read through it and sounded like one but my point still stands.
> 
> thank you for understanding
> Kind regards

When you start the program it says type config to configure it, which it then has numbered options, you type the number for the one you want to choose.

Due to this being a hobby project, I did not include a GUI and it is not easy to navigate the settings.

**Comment by loljeffer** [comment]
Sorry I didn’t see it, my bad  Thank you Sent from Mail for Windows 10 From: EthorbitSent: Saturday, 21 November 2020 9:18 PMTo: Ethorbit/Anti-AFKCc: loljeffer; AuthorSubject: Re: [Ethorbit/Anti-AFK] how to run it? (#6) The "README" file doesn't tell how to configure a key bind or change any of the settings. I do not code so I dont really understand the c++ code or how it works. not trying to sound like a karen, saying this cause i read through it and sounded like one but my point still stands.thank you for understandingKind regardsWhen you start the program it says type config to configure it, which it then has numbered options, you type the number for the one you want to choose.Due to this being a hobby project, I did not include a GUI and it is not easy to navigate the settings.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
